### ISSUE TITLE
Use of GT hand_center_3d and GT cam_intr

### ISSUE THREAD

**Issue by dqj5182** [zerchen/gSDF#11]
During test.py of gSDF (hsdf_osdf_2net_pa), the model seems to be utilizing "hand_center_3d" and "cam_intr" (from metas, which is GT) for transforming the predicted coordinates into camera space. Is it fair to utilize such information when prior works utilize predicted "hand center" and predicted "camera pose"?

This question is referring to below code lines.
https://github.com/zerchen/gSDF/blob/05101b5bde6765e9168026cff853b74a1412c125/playground/hsdf_osdf_2net_pa/net.py#L49

https://github.com/zerchen/gSDF/blob/05101b5bde6765e9168026cff853b74a1412c125/playground/hsdf_osdf_2net_pa/net.py#L131

https://github.com/zerchen/gSDF/blob/05101b5bde6765e9168026cff853b74a1412c125/playground/hsdf_osdf_2net_pa/net.py#L156

**Comment by zerchen** [comment]
Hi,
 
Thanks for your questions. Yes, the model assumes the access to the 3D hand center and camera intrinsics to do the 3D reconstruction. I think the comparison is reasonable. Actually, different methods predict the 3D meshes in different coordinate meshes. For example, [Grasping field](https://arxiv.org/abs/2008.04451) and [HO](https://arxiv.org/abs/1904.05767) reconstructs meshes in a local coorddinate system, while this model reconstruct] meshes in camera space, which is more challenging. Also, other 3D papers have similar assumptions (e.g., many 3D human body pose estimation papers). Instead of using GTs, actually there are many alternatives to predict 3D hand center, which is not the focus of this paper. You could have a look at [this](https://geopavlakos.github.io/projects/volumetric/files/volumetric-supp.pdf) or [this paper](https://arxiv.org/abs/1804.09534) for a reference.
