### ISSUE TITLE
Releasing mesh_hand & mesh_obj for training set

### ISSUE THREAD

**Issue by dqj5182** [zerchen/gSDF#14]
Thank you for your great work!

I just realized that mesh_hand & mesh_obj are not provided for training set of both ObMan and DexYCB dataset. Could you release them or let us know how to process the data?

**Comment by zerchen** [comment]
Thanks for your interests. I won't release the hand mesh and object mesh in the training set since they would take a lot of disk space and be slow to upload to google drive. I think you could obtain them by processing the dataset. Here are my experience:
For obman, I think you could refer to this [obman repo](https://github.com/hassony2/obman) for visualizing and processing meshes.
For dexycb, I think you could have a lot at my code [here](https://github.com/zerchen/gSDF/blob/master/preprocess/cocoify_dexycb.py), which could be slightly modified for your purpose.
Hope it helps.
